"""unifiedpush device endpoint

Revision ID: 206d8ebcbcd0
Revises: 7fca44eeb2c3
Create Date: 2026-09-15 17:36:05.866319
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '206d8ebcbcd0'
down_revision: str | None = '7fca44eeb2c3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('push_endpoint', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'push_endpoint')
    # ### end Alembic commands ###
