"""phase7 actions responses

Revision ID: 7d1b9777404c
Revises: bc7c85d4581a
Create Date: 2026-09-14 19:30:14.480826
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '7d1b9777404c'
down_revision: str | None = 'bc7c85d4581a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_responses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('notification_id', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('action_id', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_responses_notification_id'), 'notification_responses', ['notification_id'], unique=False)
    op.add_column('notifications', sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('notifications', sa.Column('resolved_action_id', sa.String(), nullable=True))
    op.add_column('notifications', sa.Column('responded_by_device_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'responded_by_device_id')
    op.drop_column('notifications', 'resolved_action_id')
    op.drop_column('notifications', 'resolved_at')
    op.drop_index(op.f('ix_notification_responses_notification_id'), table_name='notification_responses')
    op.drop_table('notification_responses')
    # ### end Alembic commands ###
