"""phase8 app settings

Revision ID: 7fca44eeb2c3
Revises: 7d1b9777404c
Create Date: 2026-09-15 16:45:02.197460
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '7fca44eeb2c3'
down_revision: str | None = '7d1b9777404c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_settings')
    # ### end Alembic commands ###
