"""phase5 audio assets

Revision ID: bc7c85d4581a
Revises: 11a99677dcd4
Create Date: 2026-09-14 19:03:46.348962
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'bc7c85d4581a'
down_revision: str | None = '11a99677dcd4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_assets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_assets_user_id'), 'audio_assets', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audio_assets_user_id'), table_name='audio_assets')
    op.drop_table('audio_assets')
    # ### end Alembic commands ###
